import AppKit
import SuseCore

struct ClipboardSource: Sendable {
    let name: String
    let bundleIdentifier: String?

    @MainActor static func frontmost() -> ClipboardSource {
        let application = NSWorkspace.shared.frontmostApplication
        return ClipboardSource(name: application?.localizedName ?? "未知应用", bundleIdentifier: application?.bundleIdentifier)
    }
}

@MainActor
final class ClipboardStore: ClipboardListing {
    private let settings: SettingsStore
    private let pasteboard: NSPasteboard
    private let disk: ClipboardDisk
    private let sourceProvider: @MainActor () -> ClipboardSource
    private var timer: Timer?
    private var writeTask: Task<Void, Never>?
    private var startTask: Task<Void, Never>?
    private var lastChange: Int
    private(set) var persistenceError: String?
    var onChange: (() -> Void)?
    var onExplicitRemoval: ((UUID?) -> Void)?

    var countLimit: Int { settings.clipboardLimit }
    var pasteboardChangeCount: Int { pasteboard.changeCount }

    var accessNotice: String? {
        switch pasteboard.accessBehavior {
        case .alwaysDeny: "系统已阻止读取剪贴板，请在系统隐私设置中允许 \(AppIdentity.name)。"
        case .ask, .default: "自动记录需允许读取剪贴板；可在系统隐私设置中为 \(AppIdentity.name) 设为始终允许。"
        case .alwaysAllow: nil
        @unknown default: nil
        }
    }

    init(settings: SettingsStore, pasteboard: NSPasteboard = .general,
         persistenceURL: URL = URL.applicationSupportDirectory.appending(path: "Suse/clipboard-history.sqlite"),
         source: @escaping @MainActor () -> ClipboardSource = ClipboardSource.frontmost) {
        self.settings = settings
        self.pasteboard = pasteboard
        disk = ClipboardDisk(url: persistenceURL)
        sourceProvider = source
        lastChange = pasteboard.changeCount
    }

    func start() {
        guard startTask == nil else { return }
        let limit = countLimit
        let preparation = enqueue { try await $0.prepare(limit: limit) }
        startTask = Task { [weak self] in
            _ = await preparation.value
            guard let self, !Task.isCancelled else { return }
            timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated { self?.checkForChanges() }
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        startTask?.cancel()
        startTask = nil
    }

    /// Accepted writes are never cancelled by a panel closing or by application shutdown.
    func flush() async { await writeTask?.value }

    func settingsChanged() { lastChange = pasteboard.changeCount; onChange?() }

    func page(query: String = "", offset: Int = 0, limit: Int = 100) async throws -> ClipboardPage {
        await flush()
        try Task.checkCancellation()
        return try await disk.page(query: query, offset: offset, limit: limit)
    }

    func index(of id: UUID, query: String) async throws -> Int? {
        await flush()
        try Task.checkCancellation()
        return try await disk.index(of: id, query: query)
    }

    func content(for record: ClipboardRecord) async throws -> ClipboardEntry {
        await flush()
        try Task.checkCancellation()
        return try await disk.content(for: record)
    }

    func checkForChanges() {
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        guard settings.defaults.bool(forKey: "clipboard.enabled") else { return }
        guard pasteboard.accessBehavior != .alwaysDeny else { onChange?(); return }
        let excluded = settings.defaults.string(forKey: "clipboard.excludedApps") ?? ""
        let source = sourceProvider()
        let identifiers = excluded.split(whereSeparator: { $0 == "\n" || $0 == "," }).map { $0.trimmingCharacters(in: .whitespaces) }
        guard !identifiers.contains(source.bundleIdentifier ?? "") else { return }
        if settings.defaults.bool(forKey: "clipboard.ignoreSensitive") {
            let sensitive = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                             "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
            guard !(pasteboard.types ?? []).contains(where: { sensitive.contains($0.rawValue) }) else { return }
        }
        let content: ClipboardContent
        var convertImage = false
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            content = .text(text)
        } else if let data = pasteboard.data(forType: .png), !data.isEmpty {
            content = .image(data)
        } else if let data = pasteboard.data(forType: .tiff), !data.isEmpty {
            content = .image(data)
            convertImage = true
        } else { return }
        let entry = ClipboardEntry(content: content, source: source.name)
        let settings = settings
        let needsConversion = convertImage
        enqueue { try await $0.capture(entry, limit: settings.clipboardLimit, convertImage: needsConversion) }
    }

    func copy(_ entry: ClipboardEntry, expectedChangeCount: Int? = nil) -> Bool {
        if let expectedChangeCount, pasteboard.changeCount != expectedChangeCount { return false }
        pasteboard.clearContents()
        let success: Bool
        switch entry.content {
        case .text(let text): success = pasteboard.setString(text, forType: .string)
        case .image(let png): success = pasteboard.setData(png, forType: .png)
        }
        lastChange = pasteboard.changeCount
        return success
    }

    func edit(_ record: ClipboardRecord, text: String) async -> Bool {
        let settings = settings
        let result = await enqueue { try await $0.edit(record, text: text, limit: settings.clipboardLimit) }.value
        if case .success = result { return true }
        return false
    }

    func setPinned(_ record: ClipboardRecord, pinned: Bool) {
        let settings = settings
        enqueue { try await $0.setPinned(id: record.id, pinned: pinned, limit: settings.clipboardLimit) }
    }

    func movePinned(id: UUID, before nextID: UUID?) {
        enqueue { try await $0.movePinned(id: id, before: nextID) }
    }

    func remove(_ record: ClipboardRecord) {
        enqueue({ try await $0.remove(id: record.id) }, completion: { [weak self] _ in self?.onExplicitRemoval?(record.id) })
    }

    func clear() {
        enqueue({ try await $0.clear() }, completion: { [weak self] _ in self?.onExplicitRemoval?(nil) })
    }

    func retentionPlan(limit: Int) async throws -> ClipboardRetentionPlan {
        await flush()
        return try await disk.retentionPlan(limit: limit)
    }

    func applyRetention(_ plan: ClipboardRetentionPlan) async throws -> ClipboardRetentionPlan? {
        let result = await enqueue({ try await $0.applyRetention(plan) }, completion: { [weak self] revisedPlan in
            if revisedPlan == nil { self?.settings.defaults.set(plan.limit, forKey: "clipboard.limit") }
        }).value
        return try result.get()
    }

    func counts() async throws -> (pinned: Int, ordinary: Int) {
        await flush()
        return try await disk.counts()
    }

    @discardableResult
    private func enqueue<T: Sendable>(_ operation: @escaping @MainActor @Sendable (ClipboardDisk) async throws -> T,
                                      completion: (@MainActor (T) -> Void)? = nil) -> Task<Result<T, Error>, Never> {
        let preceding = writeTask
        let task = Task<Result<T, Error>, Never> { [weak self, disk] in
            await preceding?.value
            do {
                let value = try await operation(disk)
                self?.persistenceError = nil
                completion?(value)
                self?.onChange?()
                return .success(value)
            } catch {
                self?.persistenceError = error.localizedDescription
                self?.onChange?()
                return .failure(error)
            }
        }
        writeTask = Task { _ = await task.value }
        return task
    }
}
