import AppKit
import SuseCore

private actor ClipboardDisk {
    private var lastRevision = -1
    private let url: URL
    init(url: URL) { self.url = url }

    func load() throws -> [ClipboardEntry] {
        guard FileManager.default.fileExists(atPath: url.path) else { return [] }
        let size = try url.resourceValues(forKeys: [.fileSizeKey]).fileSize ?? 0
        // JSON can expand a control character to six bytes; accept every valid bounded history.
        guard size <= 196 * 1_024 * 1_024 else { throw AppError("剪贴板历史文件过大，已跳过加载。") }
        return try JSONDecoder().decode([ClipboardEntry].self, from: Data(contentsOf: url))
    }

    func save(_ entries: [ClipboardEntry]?, revision: Int) throws {
        guard revision > lastRevision else { return }
        lastRevision = revision
        if let entries {
            try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true,
                                                    attributes: [.posixPermissions: 0o700])
            try JSONEncoder().encode(entries).write(to: url, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        } else if FileManager.default.fileExists(atPath: url.path) {
            try FileManager.default.removeItem(at: url)
        }
    }
}

@MainActor
final class ClipboardStore {
    private let settings: SettingsStore
    private let pasteboard: NSPasteboard
    private let disk: ClipboardDisk
    private var timer: Timer?
    private var saveTask: Task<Void, Never>?
    private var startTask: Task<Void, Never>?
    private var lastChange: Int
    private var revision = 0
    private(set) var history: ClipboardHistory
    private(set) var persistenceError: String?
    var onChange: (() -> Void)?

    var accessNotice: String? {
        switch pasteboard.accessBehavior {
        case .alwaysDeny: "系统已阻止读取剪贴板，请在系统隐私设置中允许 Suse。"
        case .ask, .default: "自动记录需允许读取剪贴板；可在系统隐私设置中为 Suse 设为始终允许。"
        case .alwaysAllow: nil
        @unknown default: nil
        }
    }

    init(settings: SettingsStore, pasteboard: NSPasteboard = .general,
         persistenceURL: URL = URL.applicationSupportDirectory.appending(path: "Suse/clipboard-history.json")) {
        self.settings = settings
        self.pasteboard = pasteboard
        disk = ClipboardDisk(url: persistenceURL)
        lastChange = pasteboard.changeCount
        history = ClipboardHistory(countLimit: settings.defaults.integer(forKey: "clipboard.limit"))
    }

    func start() {
        startTask = Task { [weak self] in
            guard let self else { return }
            if settings.defaults.bool(forKey: "clipboard.persist") {
                let startingRevision = revision
                do {
                    let saved = try await disk.load()
                    if !Task.isCancelled, startingRevision == revision,
                       settings.defaults.bool(forKey: "clipboard.persist") { history.restore(saved) }
                }
                catch { persistenceError = error.localizedDescription }
            } else {
                do { try await disk.save(nil, revision: revision) }
                catch { persistenceError = error.localizedDescription }
            }
            guard !Task.isCancelled else { return }
            onChange?()
            timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
                MainActor.assumeIsolated { self?.checkForChanges() }
            }
        }
    }

    func stop() { timer?.invalidate(); timer = nil; startTask?.cancel() }
    func flush() async { await saveTask?.value }

    func settingsChanged() {
        history.countLimit = settings.defaults.integer(forKey: "clipboard.limit")
        lastChange = pasteboard.changeCount
        changed()
    }

    func checkForChanges() {
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        guard settings.defaults.bool(forKey: "clipboard.enabled") else { return }
        guard pasteboard.accessBehavior != .alwaysDeny else { onChange?(); return }
        let excluded = settings.defaults.string(forKey: "clipboard.excludedApps") ?? ""
        let source = NSWorkspace.shared.frontmostApplication
        let identifiers = excluded.split(whereSeparator: { $0 == "\n" || $0 == "," }).map { $0.trimmingCharacters(in: .whitespaces) }
        guard !identifiers.contains(source?.bundleIdentifier ?? "") else { return }
        if settings.defaults.bool(forKey: "clipboard.ignoreSensitive") {
            let sensitive = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                             "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
            guard !(pasteboard.types ?? []).contains(where: { sensitive.contains($0.rawValue) }) else { return }
        }
        let content: ClipboardContent
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            content = .text(text)
        } else if let data = pasteboard.data(forType: .png), data.count <= history.itemByteLimit {
            content = .image(data)
        } else if let data = pasteboard.data(forType: .tiff), data.count <= history.itemByteLimit,
                  let representation = NSBitmapImageRep(data: data),
                  let png = representation.representation(using: .png, properties: [:]) {
            content = .image(png)
        } else { return }
        if history.insert(ClipboardEntry(content: content, source: source?.localizedName ?? "未知应用")) { changed() }
    }

    func copy(_ entry: ClipboardEntry) -> Bool {
        pasteboard.clearContents()
        let success: Bool
        switch entry.content {
        case .text(let text): success = pasteboard.setString(text, forType: .string)
        case .image(let png): success = pasteboard.setData(png, forType: .png)
        }
        lastChange = pasteboard.changeCount
        return success
    }

    func edit(_ entry: ClipboardEntry, text: String) -> Bool {
        guard history.edit(id: entry.id, text: text) else { return false }
        changed()
        return true
    }

    func remove(_ entry: ClipboardEntry) { history.remove(id: entry.id); changed() }
    func clear() { history.removeAll(); changed() }

    private func changed() {
        onChange?()
        revision += 1
        let version = revision
        let snapshot = settings.defaults.bool(forKey: "clipboard.persist") ? history.entries : nil
        saveTask?.cancel()
        saveTask = Task { [weak self, disk] in
            do {
                // Coalesce rapid clipboard changes, keeping disk operations ordered by revision.
                if snapshot != nil { try await Task.sleep(for: .milliseconds(250)) }
                try Task.checkCancellation()
                try await disk.save(snapshot, revision: version)
                self?.persistenceError = nil
            } catch is CancellationError { }
            catch {
                self?.persistenceError = error.localizedDescription
                self?.onChange?()
            }
        }
    }
}
